import React, { useState } from "react";
import { db } from "./firebase";
import { collection, addDoc } from "firebase/firestore";
import { getFunctions, httpsCallable } from "firebase/functions";

function App() {
  const [formState, setFormState] = useState({
    firstNumber: "",
    secondNumber: "",
  });

  const handleChange = (event) => {
    setFormState({
      ...formState,
      [event.target.name]: event.target.value,
    });
  };

  const inputEmpty = () => {
    return formState.firstNumber === "" || formState.secondNumber === "";
  };

  const addToDB = async () => {
    if (inputEmpty()) {
      window.alert("The input is Empty");
    } else {
      try {
        let docRef = await addDoc(collection(db, "nums"), {
          firstNumber: parseInt(formState.firstNumber),
          secondNumber: parseInt(formState.secondNumber),
        });
        console.log("Document written with ID: ", docRef.id);
      } catch (e) {
        console.error("Error adding document: ", e);
      }

      console.log("add to db with: " + JSON.stringify(formState));
    }
  };

  const callFunction = () => {
    if (inputEmpty()) {
      window.alert("The input is Empty");
    } else {
      const functions = getFunctions();

      const sumNumbers = httpsCallable(functions, "sumNumbers");
      sumNumbers({
        firstNumber: parseInt(formState.firstNumber),
        secondNumber: parseInt(formState.secondNumber),
      }).then((result) => {
        window.alert(`The sum is ${result.data}`);
      });
    }
  };

  return (
    <>
      <h1>React+Firebase integration demo</h1>
      <ul>
        Enter two integers in the input forms below.
        <li>
          <b>Add to Firestore DB</b>: Adds the two numbers into the Firestore
          database. The Collection name is "nums," the document name is
          autogenerated, and the key names are firstNumber and secondNumber.
        </li>
        <li>
          <b>Compute Sum with Cloud Function</b>: Uses a cloud function to
          compute the sum of the First and the Second Number and responds with
          the result
        </li>
      </ul>
      <label>
        First Number:{" "}
        <input
          type="number"
          name="firstNumber"
          value={formState.firstNumber}
          onChange={handleChange}
        />
      </label>
      &nbsp; &nbsp;
      <label>
        Second Number:{" "}
        <input
          type="number"
          name="secondNumber"
          value={formState.secondNumber}
          onChange={handleChange}
        />
      </label>
      <br /> <br />
      <p>
        <code>{JSON.stringify(formState)}</code>
      </p>
      <br /> <br />
      <button onClick={addToDB}>Add to Firestore DB</button> &nbsp; &nbsp;
      <button onClick={callFunction}>Compute Sum with Cloud Function</button>
    </>
  );
}

export default App;